In [12]:
import altair as alt
from vega_datasets import data
import pandas as pd

In [4]:
stocks = data.stocks()
stocks.head()

  symbol       date  price
0   MSFT 2000-01-01  39.81
1   MSFT 2000-02-01  36.35
2   MSFT 2000-03-01  43.22
3   MSFT 2000-04-01  28.37
4   MSFT 2000-05-01  25.45

In [27]:
stock_title = alt.TitleParams(
    "Google's stock experiencing heavier fluctuations than competitors",
    subtitle="Prices have been surging since 2009, but have still not reached"
)

stock_max_date = stocks[stocks['date'] == stocks['date'].max()]
print (stock_max_date)
stock_max_date. loc[stock_max_date['symbol'] == "IBM", 'price'] = 140
stock_max_date. loc[stock_max_date['symbol'] == "AMZN", 'price'] = 110

texts = alt. Chart(stock_max_date).mark_text(align='left', dx=2).encode(
    x='date',
    y='price',
    text='symbol',
    color=alt.Color('symbol', legend=None)
)

lines = alt. Chart(stocks, title=stock_title). mark_line(). encode(
    alt.X('date', title=None, axis=alt.Axis(tickCount=10)),
    alt.Y('price', title='Closing price', axis=alt.Axis(format='$s')),
    color = alt.Color('symbol'),
    tooltip=[
        'symbol',
        'date',
        'price',
        alt.Tooltip('price', format='$.2s')
    ]
).properties(
    width=500
)

lines + texts

    symbol       date   price
122   MSFT 2010-03-01   28.80
245   AMZN 2010-03-01  128.82
368    IBM 2010-03-01  125.55
436   GOOG 2010-03-01  560.19
559   AAPL 2010-03-01  223.02

alt.LayerChart(...)

In [1]:
import pandas as pd
import altair as alt

dataset_url = 'https://raw.githubusercontent.com/erickedu85/dataset/master/penguins.csv'
df = pd.read_csv(dataset_url)
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [10]:
print(f"Unique values in species: {df['species'].unique()}\n")
print(f"Unique values in island: {df['island'].unique()}")

Unique values in species: <StringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

Unique values in island: <StringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [6]:
print("Unique values in Col1:", df['island'].unique())

Unique values in Col1: <StringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [4]:
grafico = alt.Chart(df).mark_boxplot(
    size=40,          # Grosor de las cajas
    outliers=True     # Mostrar puntos atípicos
).encode(
    # Eje X: Especie (ocultamos el título del eje inferior para limpiar el diseño)
    x=alt.X('species:N', title=None, axis=alt.Axis(labels=False, ticks=False)),
    
    # Eje Y: Masa corporal. No empezamos en 0 para ver mejor las diferencias de distribución
    y=alt.Y('body_mass_g:Q', 
            title='Masa Corporal (gramos)', 
            scale=alt.Scale(zero=False)),
    
    # Color: Asignamos un color por especie para rápida identificación
    color=alt.Color('species:N', 
                    title='Especie', 
                    scale=alt.Scale(scheme='set2')),
    
    # Facetado (Small Multiples): Una columna por cada Isla
    column=alt.Column('island:N', 
                      title='Isla', 
                      header=alt.Header(labelOrient='bottom', titleOrient='bottom', labelFontSize=12))
    
).properties(
    width=150,  # Ancho de cada subgráfico
    height=350, # Alto de los gráficos
    title="Distribución de Masa Corporal de Pingüinos por Especie e Isla"
).configure_title(
    fontSize=18,
    anchor='start',
    offset=20
).configure_facet(
    spacing=15 # Espacio entre los paneles
).configure_view(
    stroke=None # Quitar el borde exterior de los paneles para un look más moderno
)
grafico.show()

alt.Chart(...)